#服务端口
server:
  port: 8202

spring:
  #mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booking_system_cmn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: huangziqi1999530
  #服务名
  application:
    name: service-cmn
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev

#配置mapper xml文件的路径
#mybatis-plus.mapper-locations=classpath:com/njupt/hosp/mapper/xml/*.xml
mybatis-plus:
  mapper-locations: classpath:com/njupt/cmn/mapper/xml/*.xml